services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    env_file:
      - .env
    image: backend:v1
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    ports:
      - "8501:8501"
    image: frontend:v1
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000


  mlflow:
    container_name: mlflow
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - mlflow_data:/mlflow
    command:
      [
        "mlflow",
        "server",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--backend-store-uri",
        "sqlite:////mlflow/mlflow.db",
        "--allowed-hosts",
        "*",
      ]

volumes:
  mlflow_data: