from pydantic import BaseModel, Field
from lancedb.pydantic import LanceModel, Vector
from lancedb.embeddings import get_registry
from backend.constants import EMBEDDING_MODEL
from dotenv import load_dotenv

load_dotenv()

embedding_model = get_registry().get("cohere").create(name=EMBEDDING_MODEL)

class LectureTranscript(LanceModel):
    document_name: str
    filepath: str
    content: str = embedding_model.SourceField()
    embedding: Vector(embedding_model.ndims()) = embedding_model.VectorField()

class Prompt(BaseModel):
    prompt: str = Field(
        description="The input question from the user. Treat empty strings as missing input."
    )

# LÄGG TILL DENNA KLASS:
class RagResponse(BaseModel):
    answer: str = Field(description="The answer generated by the LLM")
    filename: str = Field(description="The name of the source document")
    filepath: str = Field(description="The local path to the source document")